### ISSUE TITLE
No return to shop after payment

### ISSUE THREAD

**Issue by TrueFawkes** [patrickkivits/bunq-for-woocommerce#21]
Not so much an issue with this lovely plugin (thank you again), but payment directs you to Bunq and does not direct you back to the store.
What are the options? Opening the payment on another tab perhaps? But how.

**Comment by patrickkivits** [comment]
Hi @TrueFawkes,

This is a known issue. Unfortunately, this has stopped working for quite some time now.

In the beginning, when I created this plugin, it did redirect you back to the success page of the webshop, just like any other payment plugin. However, due to changes on bunq's side, this does not work anymore.

I think it's because bunq.me was never intended to be used the way this plugin works, as a payment method for webshops, but merely as a way to request money from friends and family.

**Comment by patrickkivits** [comment]
BTW, both the PHP SDK and bunq API still mention/accept a `redirect_url` when creating a bunqme-tab entry:

SDK: https://github.com/bunq/sdk_php/blob/develop/src/Model/Generated/Endpoint/BunqMeTabEntry.php#L110C15-L110C33

API: https://doc.bunq.com/#/bunqme-tab/CREATE_BunqmeTab_for_User_MonetaryAccount

And this plugin still passes the order return url to it:

https://github.com/patrickkivits/bunq-for-woocommerce/blob/master/bunq-for-woocommerce.php#L305
https://github.com/patrickkivits/bunq-for-woocommerce/blob/master/includes/bunq.php#L55
